### ISSUE TITLE
Initialize with non-random data

### ISSUE THREAD

**Issue by fulldecent** [fyquah95/ramear#1]
In the buffer initialization you use random data:

```
void transmit_init() {
    buffer = malloc(BUFFER_SIZE * sizeof(__m128i));
    for (uint32_t i = 0 ; i < BUFFER_SIZE ; i++) {
        buffer[i][0] = rand();
        buffer[i][1] = rand();
    }
}    
```

And later this is transferred using: 

```
for (uint32_t i = 0 ; i < BUFFER_SIZE ; i++) {
    _mm_stream_si128(
        &reg,
        *buffer_ptr
    );
    buffer_ptr = buffer_ptr + 1;
}
```

with the goal of exciting the 128-bit wide bus.

The benefit of using random data is that you should expect a wide-band signal which should not be noticed by the receiver. And because you are using amplitude modulation this is good.

Have you tried other sequences, like alternating 128-bit zeros then ones. This may provide twice the number of transitions and +3 dB signal.

**Comment by tomhartley** [comment]
This is totally reasonable - it is something we tried early on in the hackathon. At that point in the project we were just observing the output with our eyes, and we saw no noticeable change. Now we have proper receiving code setup, we could try it - and we would probably notice a difference. We need to purchase a SDR receiver first though.

**Comment by fulldecent** [comment]
Just to share, I have been using trying `reg_zero = _mm_set_epi32(0, 0, 0, 0);` and sending the same value repetitiously and it gave the same results as a random buffer.
