### ISSUE TITLE
Opposite of steriods

### ISSUE THREAD

**Issue by fulldecent** [fyquah95/ramear#2]
For the zero-bit transmission, have you tried an opposite of the `steroids` function?

```
static inline void steroids() {
    __m128i* buffer_ptr = (__m128i*) buffer;

    for (uint32_t i = 0 ; i < BUFFER_SIZE ; i++) {
        _mm_stream_si128(
            &reg,
            *buffer_ptr
        );
        // do not move the buffer pointer, just keeping sending the same data
    }
}
```

**Comment by fyquah** [comment]
What do you mean by the opposite of `steroids` ?

**Comment by fulldecent** [comment]
The code sample above sends the same data, rather than varying it.

**Comment by fyquah** [comment]
I haven't tried it - sounds like an interesting idea.

Initially, our `steroids` function simply dumps the same data, and we found that it wasn't distinguishable from not sending any signals. I am guessing doing this might reduce the varience (and hence, noise) of the reference signal.

@tomhartley has just ordered a RF receiver. We will try this out, and see how things go. Thanks for the interesting suggestion!

**Comment by fulldecent** [comment]
To be clear, the opposite would be sending `_mm_set_epi32(0, 0, 0, 0);`

**Comment by fulldecent** [comment]
I have found that the while loop is also causing some noise. This can be fixed by using a simple `sleep` call at https://github.com/fyquah95/ramear/blob/master/transmitter.c#L34

**Comment by fulldecent** [comment]
FYI, I have been working on a related project, this is implemented at https://github.com/fulldecent/system-bus-radio/blob/master/README.md and that page contains notes on sleeping.
